os:
  - linux

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor

cache:
  directories:
    - $HOME/.pub-cache

jobs:
  include:
    #    - stage: tests
    #      addons:
    #        apt:
    #          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    #          sources:
    #            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    #          packages:
    #            - fonts-droid-fallback
    #            - libstdc++6
    #      script:
    #        - echo "RUNNING TESTS"
    #        - ./flutter/bin/flutter test
    - stage: build
      language: android
      dist: trusty
      android:
        components:
          - tools
          - platform-tools
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'            
      script:
        - yes | sdkmanager --licenses
        - cd example && ../flutter/bin/flutter build apk --split-per-abi
