os:
  - linux

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback

cache:
  directories:
    - $HOME/.pub-cache

jobs:
  include:
    - stage: tests
      script:
        - echo "RUNNING TESTS"
        - ./flutter/bin/flutter test
    - stage: build
      language: android
      dist: trusty
      android:
        components:
          - tools
          - platform-tools
      script: pwd
